### ISSUE TITLE
ShadowMapPass计算时, 相机的position, frustum等计算结果为NaN

### ISSUE THREAD

**Issue by fuzhenn** [pissang/qtek#12]
在Scene中添加shadowMap后, 在第一帧中计算平行光源的位置, 坐标均为NaN
原因是因为scene的viewBoundingBoxLastFrame是空的, 所以intersection时计算结果为NaN

代码:
https://github.com/pissang/qtek/blob/master/src/prePass/ShadowMap.js#L769

重现代码:
https://jsfiddle.net/fuzhenn/fvj77xkw/

**Comment by pissang** [comment]
Fixed in https://github.com/pissang/qtek/commit/0c369bba67b1c67d2c09799131139fbc44ad7e62
