### ISSUE TITLE
How to display a triangle?

### ISSUE THREAD

**Issue by cx20** [pissang/qtek#21]
I am trying to display basic primitives using various WebGL libraries.
https://qiita.com/cx20/items/0fa19c96aa6470d98807

I would like to add qtek to the list, but I did not know how to display the triangle.
Will you give me triangle samples by qtek if possible?
![image](https://user-images.githubusercontent.com/1833979/32731907-683154aa-c8ce-11e7-889b-cf21e69b54f6.png)

**Comment by pissang** [comment]
Pleasure. Must use custom shader instead of builtin shader?

**Comment by cx20** [comment]
If there are two ways, I would like to make samples respectively.

1) Using VBO : Using custom shader
https://qiita.com/cx20/items/0fa19c96aa6470d98807#using-vbo

2) Using built-in primitive : Using builtin shader
https://qiita.com/cx20/items/0fa19c96aa6470d98807#using-built-in-primitive

**Comment by pissang** [comment]
Hi @cx20 . I just add two triangle examples. https://github.com/pissang/qtek/blob/master/example/triangle.html
https://github.com/pissang/qtek/blob/master/example/triangle_customshader.html

**Comment by cx20** [comment]
@pissang  Thank you for offering samples.
I am trying to create a rectangular sample by referring to Triangle's sample.
http://jsdo.it/cx20/OMNV
```js
var positions = [
    [-0.5, 0.5, 0.0], // v0
    [-0.5,-0.5, 0.0], // v2
    [ 0.5, 0.5, 0.0], // v1 
    [-0.5,-0.5, 0.0], // v2
    [ 0.5,-0.5, 0.0], // v3
    [ 0.5, 0.5, 0.0]  // v1 
];
var colors = [
    [1.0, 0.0, 0.0, 1.0], // v0
    [0.0, 0.0, 1.0, 1.0], // v2
    [0.0, 1.0, 0.0, 1.0], // v1
    [0.0, 0.0, 1.0, 1.0], // v2
    [1.0, 1.0, 0.0, 1.0], // v3
    [0.0, 1.0, 0.0, 1.0]  // v1
];
```
However, the array of vertex data is redundant.
I would like to rewrite to use indices, but can it be realized?

I would like to use the following array.
```js
var cositions = [
    [-0.5, 0.5, 0.0], // v0
    [ 0.5, 0.5, 0.0], // v1 
    [-0.5,-0.5, 0.0], // v2
    [ 0.5,-0.5, 0.0]  // v3
];
var colors = [
    [1.0, 0.0, 0.0, 1.0], // v0
    [0.0, 1.0, 0.0, 1.0], // v1
    [0.0, 0.0, 1.0, 1.0], // v2
    [1.0, 1.0, 0.0, 1.0]  // v3
];

var indices = [
    2, 0, 1, // v2-v0-v1
    2, 1, 3  // v2-v1-v3
];
```

**Comment by pissang** [comment]
Yes, try `initIndicesFromArray` method.
```js
var indices = [
    2, 0, 1, // v2-v0-v1
    2, 1, 3  // v2-v1-v3
];
geometry.initIndicesFromArray(indices);
```

**Comment by cx20** [comment]
@pissang Thank you for teaching me. I tried initIndicesFromArray.
However, The case of "A" is displayed, but it is not displayed in the case of "B".
Is this because qtek's default frontFace is CCW?

```js
// [0]------[1]
//  |      / |
//  |    /   |
//  |  /     |
// [2]------[3]
```

```js
// A) OK
var indices = [
    0, 2, 1, // v0-v2-v1
    1, 2, 3  // v1-v2-v3
];

// B) NG
var indices = [
    2, 0, 1, // v2-v0-v1
    2, 1, 3  // v2-v1-v3
];
```
Could you tell me how to change frontFace settings?

**Comment by pissang** [comment]
```js
mesh.frontFace = qtek.Renderable.CW
```

**Comment by cx20** [comment]
Thank you! It is now displayed as expected.
http://jsdo.it/cx20/OMNV

Next I will challenge the colored cube :)

**Comment by pissang** [comment]
Good luck! Any questions or suggestions are welcome:)

**Comment by cx20** [comment]
I was able to display textured cubes :)
http://jsdo.it/cx20/Qwbw
![image](https://user-images.githubusercontent.com/1833979/32788356-57989dc8-c99c-11e7-8b76-61974c0391d8.png)

Can you check if the library is used properly?

**Comment by cx20** [comment]
I added a sample of QTEK to the following Basic Primitives sample.
https://qiita.com/cx20/items/0fa19c96aa6470d98807
![image](https://user-images.githubusercontent.com/1833979/32789044-28301df2-c99e-11e7-812c-d5f512e84877.png)

I would like to add a sample that uses built-in shaders instead of Custom Shader at a later date.

**Comment by pissang** [comment]
Great!  I see following code:
```js
//mesh.frontFace = qtek.Renderable.CW;
mesh.culling = false;
```
Is this because the commented code can't work?

And this line is no need.
```js
var normal = new qtek.Texture2D;
```

Can't find any other problems:)

**Comment by cx20** [comment]
Thank you for confirmation.

I set culling to false because the box did not close.
If you comment out this line you will get the following result.
```js
// mesh.culling = false;
```
![image](https://user-images.githubusercontent.com/1833979/32791826-3dc63334-c9a5-11e7-967a-17bfba5f0114.png)

Perhaps the data may be bad, but since other library samples use the same VBO data, I am trying to accommodate them with parameters.

> var normal = new qtek.Texture2D;

It is a copy mistake. I removed this line.

**Comment by pissang** [comment]
Understand. Builtin in primitive and shader next? :)

**Comment by cx20** [comment]
@pissang  I added the following sample using Built-in primitive and shader.

http://jsdo.it/cx20/uObL ... Triangle
http://jsdo.it/cx20/uOIG ... Plane
http://jsdo.it/cx20/k6uv ... Cube
http://jsdo.it/cx20/4TBY ... Cube + Texture

I would like to add colors to quads and cubes if possible. Is it feasible?
http://jsdo.it/cx20/uOIG
![image](https://user-images.githubusercontent.com/1833979/32837058-55e93736-ca4f-11e7-939d-9c3a4ab9e869.png)

http://jsdo.it/cx20/k6uv ... Cube
![image](https://user-images.githubusercontent.com/1833979/32837046-4c577746-ca4f-11e7-93f7-c45ac0915e0f.png)

**Comment by pissang** [comment]
For the quads. You can use vertex colors with `standard` shader. Like following:

```js
geometry.attributes.color.fromArray([
  [1, 0, 0, 1], [1, 1, 0, 1], [0, 1, 0, 1], [0, 0, 1, 1]
]);
var mesh = new qtek.Mesh({
    geometry: geometry,
    material: new qtek.Material({
        // Use standard shader
        shader: qtek.shader.library.get('qtek.standard')
    })
});
// Enable vertex color in both vertex and fragment shader.
mesh.material.shader.define('both', 'VERTEX_COLOR');
```

For the cubes. You can alose use vertex colors like quads. Or render the normals. Which is simpler.

```js
var mesh = new qtek.Mesh({
    geometry: geometry,
    material: new qtek.Material({
        // Only lambert shader support normal output
        shader: qtek.shader.library.get('qtek.lambert')
    })
});
mesh.material.shader.define('fragment', 'RENDER_NORMAL');
```

**Comment by cx20** [comment]
@pissang Very Thanks! I will try vertex colors.

**Comment by cx20** [comment]
Hmm. Somehow I am not going well.
I am trying vertex colors in the case of quads, but it seems that an error occurs.
http://jsrun.it/cx20/yupZc
```js
qtek.js:21169 
Uncaught Error: Could not link program
VALIDATE_STATUS: false, gl error [0]
    at sub.renderQueue (qtek.js:21169)
    at sub.render (qtek.js:21009)
    at sub.<anonymous> (index.js:41)
    at sub.trigger (qtek.js:146)
    at sub._update (qtek.js:1788)
    at step (qtek.js:1811)
```

**Comment by pissang** [comment]
I can't open the link. Can you paste the code here?

**Comment by pissang** [comment]
Hmm, it seems to be a bug. Sorry about that

**Comment by cx20** [comment]
http://jsdo.it/cx20/yupZc ... Editor
http://jsrun.it/cx20/yupZc .. Run mode

**Comment by cx20** [comment]
Is it because the v_Color variable is not defined in the Frangment Shader?
https://github.com/pissang/qtek/blob/4ce02974992397fc9388c8d2812cb8996caea0fa/src/shader/source/standard.glsl#L43-L45

**Comment by pissang** [comment]
Fixed. You can pull the latest code and rebuild with command `npm install && npm run build`. I also add vertex color in `basic` shader. So there is no need to use standard shader, which also need a light in scene or it will be black. See example https://github.com/pissang/qtek/blob/master/example/triangle_vertexcolor.html

**Comment by pissang** [comment]
@cx20 Yeah that's the issue. Never tested this branch before, My bad:(

**Comment by fuzhenn** [comment]
Good catch! 
@pissang I think it deserves to add a test case into the integration test suite.

**Comment by pissang** [comment]
@fuzhenn True

**Comment by cx20** [comment]
I was able to set Vertex Colors in the sample below.

http://jsdo.it/cx20/uOIG
http://jsdo.it/cx20/k6uv

I added samples of built-in primitive and shader below.
https://qiita.com/cx20/items/0fa19c96aa6470d98807#using-built-in-primitive
![image](https://user-images.githubusercontent.com/1833979/32842675-05884090-ca61-11e7-9661-1ad3cbf11133.png)

**Comment by cx20** [comment]
Since the triangle is now displayed, this Issue is closed.

Perhaps I will add a sample with the physics library next.
https://qiita.com/cx20/items/3ebed669fb9c9e797935

**Comment by pissang** [comment]
Looking forward to it!!

**Comment by cx20** [comment]
@pissang  BTW, I added 3 samples using the physical library to the above [list](https://qiita.com/cx20/items/3ebed669fb9c9e797935).

http://jsdo.it/cx20/qtGf ... domino
http://jsdo.it/cx20/s2wJ ... football
http://jsdo.it/cx20/6viZ ... box

**Comment by pissang** [comment]
@cx20 Wow!! Well done!
