### ISSUE TITLE
How to use quaternions?

### ISSUE THREAD

**Issue by cx20** [pissang/qtek#27]
Below is a sample of Quaternion using Three.js.
http://jsdo.it/cx20/qqSi

```js
function render() {

    // rotate
    mesh1.rotation.x += Math.PI / 180;
    mesh1.rotation.y += Math.PI / 180;
    mesh1.rotation.z += Math.PI / 180;
    
    // quaternion
    var axis = new THREE.Vector3(1,1,1).normalize();
    angle += Math.PI / 180;
    var q = new THREE.Quaternion();
    q.setFromAxisAngle(axis,angle);
    mesh2.quaternion.copy(q);

    // render
    renderer.render( scene, camera );

}
```

How can I write code in QTEK to do the same?

**Comment by pissang** [comment]
In qtek, `mesh.rotation` is a quaternion.

All methods of the quaternion can be found in http://pissang.github.io/qtek/doc/api/qtek.math.Quaternion.html . And `setAxisAngle` is one of them.

If you want to use Euler angle. http://pissang.github.io/qtek/doc/api/qtek.math.Quaternion.html#.fromEuler is an option

**Comment by cx20** [comment]
I understood that mesh.rotation is quaternion.
I was able to port from Three.js to qtek.
http://jsdo.it/cx20/wvM6A
```js
animation.on('frame', function(deltaTime) {
    var drawInfo = renderer.render(scene, camera);
    // euler
    mesh1.rotation.fromEuler(new qtek.math.Vector3(rad, rad, rad), "XYZ");

    // quaternion
    mesh2.rotation.rotateX(Math.PI/180);
    mesh2.rotation.rotateY(Math.PI/180);
    mesh2.rotation.rotateZ(Math.PI/180);

    rad += Math.PI/180;
});
```
