### ISSUE TITLE
How can I make the wall transparent?

### ISSUE THREAD

**Issue by cx20** [pissang/qtek#28]
I tried to make a sample to put the ball in the box.
However, I did not know how to make the box transparent.
I wanted to make a sample that would give results similar to Three.js.
Could you tell me how to make the box transparent?

[QTEK + Ball in the Box sample:](http://jsdo.it/cx20/yZwE)
![image](https://user-images.githubusercontent.com/1833979/32992329-af24c2c6-cd8c-11e7-9368-24161987b1a7.png)

[Three.js + Ball in the Box sample:](http://jsdo.it/cx20/kNgw)
![image](https://user-images.githubusercontent.com/1833979/32992398-8e0c77ae-cd8d-11e7-80bb-63e35bd20b4e.png)

**Comment by pissang** [comment]
Try:
```js
material.depthMask = false;
material.transparent = true;
material.set('alpha', 0.5);
```

**Comment by cx20** [comment]
@pissang I was able to make the box translucent in the way you taught me :)

[QTEK + Ball in the Box sample:](http://jsdo.it/cx20/yZwE)
![image](https://user-images.githubusercontent.com/1833979/32993158-954c9c6a-cd97-11e7-842f-4eb7d533ba8f.png)

**Comment by cx20** [comment]
Also, Could you please tell me how to shade the ball if possible?

**Comment by pissang** [comment]
I've checked the code and the `intensity` of ambient light is too large. `0.4` is ok.

**Comment by cx20** [comment]
@pissang Excellent! I was able to display shadows. Thanks!

[QTEK + Ball in the Box sample:](http://jsdo.it/cx20/yZwE)
![image](https://user-images.githubusercontent.com/1833979/33018686-bb9ff0f8-ce3a-11e7-986e-5893e78a4963.png)
