### ISSUE TITLE
Several examples do not work (missing lib/require.js)

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [pissang/qtek#29]
Hi,

Several examples do not work because the require.js file can't be found:
- https://pissang.github.io/qtek/example/gltf2.html
- https://pissang.github.io/qtek/example/IBL.html
- https://pissang.github.io/qtek/example/standard_material.html

No directory of `lib` exists with the required Require.js file.
```
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script type="text/javascript" src="lib/require.js"></script>
    </head>
```

Possible other files that are missing the `lib` folder can be found using the following search query:
https://github.com/pissang/qtek/search?utf8=%E2%9C%93&q=%2Flib%2Frequire.js&type=

Thank you for the great library, it has been a great inspiration.

Tim

**Comment by pissang** [comment]
Thanks for the feedback!! The `lib` folder was ignored unexpectedly. Just submitted the `lib` folder and the examples work well now.

**Comment by TimvanScherpenzeel** [comment]
Oh great, I'll close my pull request. 

Thanks 👍
