### ISSUE TITLE
PBR implementation?

### ISSUE THREAD

**Issue by amerkoleci** [pissang/qtek#4]
Hi,
I saw you've added PBR support and it is standard shader now, it is fully implemented?
I saw functions like G_Smith, D_GGX never called?
Whats missing?

Thanks

**Comment by pissang** [comment]
Hi @amerkoleci 

I've tried several normal distribution functions. And now in the shader is the classic Phong distribution. In the slides [Getting More Physical in Call of Duty: Black Ops II ](http://blog.selfshadow.com/publications/s2013-shading-course/lazarov/s2013_pbs_black_ops_2_slides_v2.pdf) there is a detail explanation.

About IBL in physically based rendering. I tried it in the late 2013 in [example](http://pissang.github.io/qtek/tests/IBL.html) . But at that time WebGL still has no extesion for textureCubeLod(https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod/). So there is no further try.
