### ISSUE TITLE
咨询一个echarts的问题

### ISSUE THREAD

**Issue by yhhwpp** [pissang/qtek#6]
hi， Yi Shen，你好，请教你一个echarts的问题。

我现在的一个需求是图表的可以在X轴方向上可以拖动，在Y轴不可以。

我的dataZoom事件设置‘inside’（因为项目需求，只能用inside，不能用slider），设置了zoomLock 为true后，现在我发现在移动端，Y轴方向拖动屏幕时，dataZoom事件会跟原生的拖动事件冲突，造成在图表区域内Y轴方向拖动时，不能拖动屏幕。我想取消dataZoom在Y轴上的事件，请问我改怎么做呢。
盼回复，谢谢！！

**Comment by pissang** [comment]
请在 https://github.com/ecomfe/echarts 咨询，谢谢
