### ISSUE TITLE
npm未发布更新0.4.0

### ISSUE THREAD

**Issue by sugaE** [pissang/qtek#7]
现在是2017-7-11 18:43

我刚刚给项目装了一下node modules，安装的依赖中有对qtek最低0.4.0版本的依赖，但npm上(https://www.npmjs.com/package/qtek )没有更新最新版本。

<img width="402" alt="wx20170711-184641 2x" src="https://user-images.githubusercontent.com/10446823/28064953-2287b88a-6669-11e7-92a8-a2d67e7a224c.png">

<img width="456" alt="wx20170711-184501 2x" src="https://user-images.githubusercontent.com/10446823/28064952-2275cabc-6669-11e7-9b9a-1e8e830bdb2a.png">

**Comment by pissang** [comment]
已发布
